car-rental/Controllers/AuthenticationController.cs
using car_rental.application.Common.Interface;
using car_rental.application.DTOs;
using car_rental.domain.Entities;
using CarRentalSystem.Application.Common.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace car_rental.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IUserService _userService;
        private readonly IFileService _fileService;
        private readonly IUnitOfWork _unitOfWork;

        public AuthenticationController(UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            SignInManager<IdentityUser> signInManager,
            IUserService userService,
            IUnitOfWork unitOfWork,
            IFileService fileService
        )
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _unitOfWork = unitOfWork;
            _userService = userService;
            _fileService = fileService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Register()
        {
            //ViewData["ReturnUrl"] = returnUrl;

            var register = new CustomerRegisterDTO();

            return View(register);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(CustomerRegisterDTO model)
        {
            var userInDb = await _userManager.FindByEmailAsync(model.Email);

            if (userInDb == null)
            {
                var user = new User
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    UserName= model.Email,
                    EmailConfirmed = true,

                };
                var result = await _userManager.CreateAsync(user, model.Password);
                await _userManager.AddToRoleAsync(user, "Customer");
                var customer = new Customer();

                if (result.Succeeded)
                {
                    customer.UserId = user.Id;
                     _unitOfWork.Customer.Add(customer);
                    await _unitOfWork.SaveChangesAsync();
                }
            }
            return RedirectToAction("Landing", "Home");
        }

        //Staff Reg 
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> RegisterStaff()
        {
            //ViewData["ReturnUrl"] = returnUrl;

            var register = new StaffRegisterDTO();

            return View(register);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterStaff(StaffRegisterDTO model)
        {
            var userInDb = await _userManager.FindByEmailAsync(model.Email);

            if (userInDb == null)
            {
                var user = new User
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    UserName = model.Email,
                    EmailConfirmed = true,

                };
                var result = await _userManager.CreateAsync(user, model.Password);
                await _userManager.AddToRoleAsync(user, "Staff");
                var staff = new Staff();

                if (result.Succeeded)
                {
                    staff.UserId = user.Id;
                    _unitOfWork.Staff.Add(staff);
                    await _unitOfWork.SaveChangesAsync();
                }
            }
            return RedirectToAction("AdminDashboard", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnurl = null)
        {
            ViewData["ReturnUrl"] = returnurl;

            var login = new UserLoginRequestDTO();

            return View(login);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginRequestDTO model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            returnUrl ??= Url.Content("~/");

            var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: true);

            if (result.Succeeded)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                var roles = await _userManager.GetRolesAsync(user);
              
                return LocalRedirect(returnUrl);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View(model);
            }
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Landing","Home");
        }









        //[HttpGet]
        //public IActionResult Profile()
        //{
        //    ProfileDTO model = new ProfileDTO();
        //    var claimsIdentity = (ClaimsIdentity)User.Identity;
        //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        //    var user = new string(claim.Value);
        //    var customer = _unitOfWork.Customer.GetFirstOrDefault(x => x.UserId == user);
        //    var documentName = _userService.GetDocument(user);
        //    if (documentName != "")
        //    {
        //        model.ExistingDocumentName = documentName;
        //    }

        //    return View(model);
        //}

        //[Authorize]
        //[HttpPost]
        //public IActionResult Profile(ProfileDTO model)
        //{
        //    var claimsIdentity = (ClaimsIdentity)User.Identity;
        //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        //    var user = new string(claim.Value);
        //    var customer = _unitOfWork.Customer.GetFirstOrDefault(x => x.UserId == user);
        //    var documentName = _userService.GetDocument(user);
        //    Document document = new Document();

        //    if (documentName == "")
        //    {

        //        if (model.DocumentUrl != null)
        //        {
        //            var result = _fileService.SaveImage(model.DocumentUrl);
        //            if (result.Item1 == 1)
        //            {
        //                document.DocumentName = result.Item2;
        //                document.CustomerId = customer.Id;
        //            }
        //            document.DocumentType = model.DocumentType;
        //            _unitOfWork.Document.Add(document);
        //            _unitOfWork.SaveChangesAsync();

        //        }

        //    }




        //[HttpGet]
        //public IActionResult ChangePassword()
        //{
        //    ChangePasswordDTO model = new ChangePasswordDTO();


        //    return View(model);
        //}
        //[HttpPost]
        //public async Task<IActionResult> ChangePassword(ChangePasswordDTO model)
        //{
        //    var user = await _userManager.GetUserAsync(User);
        //    var changePasswordResult = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
        //    if (!changePasswordResult.Succeeded)
        //    {
        //        foreach (var error in changePasswordResult.Errors)
        //        {
        //            //ModelState.AddModelError(string.Empty, error.Description);
        //            var errormessage = error.Description;
        //        }
        //    }

        //    await _signInManager.RefreshSignInAsync(user);
        //    return RedirectToAction("Index", "Home");

        //}






        //    return RedirectToAction("Index", "Home");

        //}
        //[HttpGet]
        //[AllowAnonymous]
        //public IActionResult RentHistory()
        //{
        //    var claimsIdentity = (ClaimsIdentity)User.Identity;
        //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        //    var user = new string(claim.Value);
        //    var customer = _unitOfWork.Customer.GetFirstOrDefault(x => x.UserId == user);
        //    var rental = _unitOfWork.Rental.GetAll().Where(x => x.CustomerId == customer.Id);

        //    return View(rental);
        //}

    }
}

car-rental/Controllers/OfferController.cs
using car_rental.application.Common.Interface;
using car_rental.application.DTOs;
using car_rental.domain.Entities;
using CarRentalSystem.Application.Common.Services;
using Microsoft.AspNetCore.Mvc;

namespace car_rental.Controllers
{
    public class OfferController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IFileService _fileService;
        private readonly IUserService _userService;
        public OfferController(IUnitOfWork unitOfWork, IFileService fileService, IUserService userService)
        {
            _unitOfWork = unitOfWork;
            _fileService = fileService;
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AdminDisplayOffer()
        {
            List<Offer> offerList = _unitOfWork.Offer.GetAll();
            return View(offerList);
        }

        [HttpGet]
        public IActionResult DisplayOffer()
        {
            List<Offer> offerList = _unitOfWork.Offer.GetAll();
            return View(offerList);
        }

        [HttpGet]
        public IActionResult AddOffer()
        {
            Offer offer = new Offer();
            return View(offer);
        }
        [HttpPost]
        public IActionResult AddOffer(OfferDTO model)
        {


            Offer offer = new Offer();

            offer.OfferName = model.OfferName;
            offer.OfferDesc = model.OfferDesc;
           



            _unitOfWork.Offer.Add(offer);
            _unitOfWork.SaveChangesAsync();

            return RedirectToAction("AdminDashboard", "Home");
        }
    }
}

car-rental/Controllers/VehicleController.cs
using car_rental.application.Common.Interface;
using car_rental.application.DTOs;
using car_rental.domain.Entities;
using CarRentalSystem.Application.Common.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace car_rental.Controllers
{
    public class VehicleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IFileService _fileService;
        private readonly IUserService _userService;
        public VehicleController(IUnitOfWork unitOfWork, IFileService fileService, IUserService userService)
        {
            _unitOfWork = unitOfWork;
            _fileService = fileService;
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AdminDisplayVehicle()
        {
            //List<Vehicle> vehicleList = _unitOfWork.Vehicle.GetAllAsync().toList;
            List<Vehicle> vehicleList = _unitOfWork.Vehicle.GetAll();
            return View(vehicleList);
        }

        [HttpGet]
        public IActionResult DisplayVehicle()
        {
            //List<Vehicle> vehicleList = _unitOfWork.Vehicle.GetAllAsync().toList;
            List<Vehicle> vehicleList = _unitOfWork.Vehicle.GetAll();
            return View(vehicleList);
        }

        [HttpGet]
        public IActionResult AddVehicle()
        {
            Vehicle vehicle = new Vehicle();
            return View(vehicle);
        }
        [HttpPost]
        public IActionResult AddVehicle(VehicleRequestDTO model)
        {
            //_unitOfWork.Vehicle.Add(vehicle);
            //_unitOfWork.SaveChangesAsync();
            //return RedirectToAction("Index", "Home");

            Vehicle vehicle = new Vehicle();


            //services.Configure<FormOptions>(options =>
            //{
            //    options.MultipartBodyLengthLimit = 1572864;
            //});

            //if (model.PhotoUrl != null)
            if (model.PhotoUrl != null && model.PhotoUrl.Length > 0)
            {
                var result = _fileService.SaveImage(model.PhotoUrl);
                if (result.Item1 == 1)
                {
                    vehicle.VehicleImage = result.Item2;
                }

            }

            vehicle.Name = model.Name;
            vehicle.Description = model.Description;
            vehicle.Color = model.Color;
            vehicle.Brand = model.Brand;
            vehicle.Rate = model.Rate;

            _unitOfWork.Vehicle.Add(vehicle);
            _unitOfWork.SaveChangesAsync();

            return RedirectToAction("AdminDashboard", "Home");
        }





        //[HttpGet]
        //public IActionResult DisplayVehicleAdmin()
        //{

        //    List<Vehicle> vehicleList = _unitOfWork.Vehicle.GetAll().Where(x => x.IsAvailable == true).ToList();

        //    return View(vehicleList);
        //}
        //[HttpGet]
        //public async Task<IActionResult> Rent(Guid id)
        //{
        //    var claimsIdentity = (ClaimsIdentity)User.Identity;
        //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        //    var user = new string(claim.Value);
        //    var customer = _unitOfWork.Customer.GetFirstOrDefault(x => x.UserId == user);
        //    var document = _userService.GetDocument(user);
        //    RentVehicleDTO model = new RentVehicleDTO();

        //    if (document != "")
        //    {
        //        model.DocumentExists = true;
        //        model.DocumentName = document;
        //    }
        //    model.Vehicle = _unitOfWork.Vehicle.Get(id);
        //    model.Vehicleid = id;
        //    model.CustomerId = customer.Id;
        //    return View(model);

        //}
        //[HttpPost]
        //public IActionResult Rent(RentVehicleDTO model)
        //{

        //    Rental rental = new Rental()
        //    {
        //        VehicleId = model.Vehicleid,
        //        CustomerId = model.CustomerId,
        //        RequestedDate = model.RequestedDate,
        //    };
        //    Document document = new Document();
        //    _unitOfWork.Vehicle.Update(model.Vehicleid);
        //    if (model.DocumentUrl != null)
        //    {
        //        var result = _fileService.SaveImage(model.DocumentUrl);
        //        if (result.Item1 == 1)
        //        {
        //            document.DocumentName = result.Item2;
        //        }
        //        document.DocumentType = model.DocumentType;
        //        document.CustomerId = model.CustomerId;
        //        _unitOfWork.Document.Add(document);


        //    }
        //    _unitOfWork.Rental.Add(rental);
        //    _unitOfWork.SaveChangesAsync();
        //    return RedirectToAction("Index", "Home");


        //}
    }
}

car-rental/Views/Shared/_Layout.cshtml
@if (User.IsInRole("Customer"))
{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - car_rental</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/a13829d471.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    </head>


    <body>
        <header class="header mb-5">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">

                    <a class="navbar-brand" class="logo" asp-area="" asp-controller="Home" asp-action="Landing"><img id="logo" src="~/img/carlogo.png" alt=""></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Landing">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="displayvehicle">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="displayoffer">Offer</a>
                            </li>
                            <partial name="_PartialLogin" />
                        </ul>
                    </div>
                </div>
            </nav>


        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


        <section class="footer">

            <div class="box-container">

                <div class="box">
                    <h3> Car Rental </h3>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam, saepe.</p>
                    <div class="share">
                        <a href="#" class="fab fa-facebook-f"></a>
                        <a href="#" class="fab fa-twitter"></a>
                        <a href="#" class="fab fa-instagram"></a>
                        <a href="#" class="fab fa-linkedin"></a>
                    </div>
                </div>

                <div class="box">
                    <h3>contact info</h3>
                    <a href="#" class="links"> <i class="fas fa-phone"></i> +123-456-7890 </a>
                    <a href="#" class="links"> <i class="fas fa-phone"></i> +111-222-3333 </a>
                    <a href="#" class="links"> <i class="fas fa-envelope"></i> abc@gmail.com </a>
                    <a href="#" class="links"> <i class="fas fa-map-marker-alt"></i> ktm, nepal - 400104 </a>
                </div>

                <div class="box">
                    <h3>quick links</h3>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> home </a>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> features </a>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> products </a>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> categories </a>
                </div>



            </div>

            <div class="credit"> created by <span> mr. web designer </span> | all rights reserved </div>

        </section>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
    </html>


}


else if (User.IsInRole("Admin") || User.IsInRole("Staff"))
{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - car_rental</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <!-- Material Icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">

        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/a13829d471.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    </head>
    <body>
        <div class="grid-container">

            <!-- Header -->
            <header class="header">
                <div class="menu-icon">
                    <span class="material-icons-outlined">menu</span>
                </div>
                <div class="header-left">
                    <span class="material-icons-outlined">search</span>
                </div>
                <div class="header-right">
                    <span class="material-icons-outlined">notifications</span>
                </div>
            </header>
            <!-- End Header -->
            <!-- Sidebar -->
            <aside id="sidebar">
                <div class="sidebar-title">
                    <div class="brand-name">
                        <p>Car rental</p>
                    </div>
                    <span class="material-icons-outlined" onclick="closeSidebar()">close</span>
                </div>

                <ul class="sidebar-list">

                    <li class="sidebar-list-item">
                        <span class="material-icons-outlined">dashboard</span> Dashboard
                    </li>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="AddVehicle">
                    <li class="sidebar-list-item">
                        
                        <span class="material-icons-outlined">
                            leaderboard
                        </span> Add Vehicle
                        
                    </li>
                    </a>
                    
                    <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="AdminDisplayVehicle">
                    <li class="sidebar-list-item">
                        <span class="material-icons-outlined">
                            badge
                        </span> List Vehicle
                    </li>
                    </a>

                    <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="AddOffer">
                    <li class="sidebar-list-item">
                        <span class="material-icons-outlined">
                            badge
                        </span> Add Offer
                    </li>
                    </a>

                    <li class="sidebar-list-item">
                        <span class="material-icons-outlined">
                            calendar_month
                        </span> Lmcwcneicn
                    </li>
                </ul>
            </aside>
            <!-- End Sidebar -->
            <!-- Main -->
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <!-- End Main -->

        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>

    </html>


}


else
{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - car_rental</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/a13829d471.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    </head>


    <body>
        <header class="header mb-5">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">

                    <a class="navbar-brand" class="logo" asp-area="" asp-controller="Home" asp-action="Landing"><img id="logo" src="~/img/carlogo.png" alt=""></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Landing">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="displayvehicle">Cars</a>
                            </li>
                            <partial name="_PartialLogin" />
                        </ul>
                    </div>
                </div>
            </nav>


        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


        <section class="footer">

            <div class="box-container">

                <div class="box">
                    <h3> Car Rental </h3>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam, saepe.</p>
                    <div class="share">
                        <a href="#" class="fab fa-facebook-f"></a>
                        <a href="#" class="fab fa-twitter"></a>
                        <a href="#" class="fab fa-instagram"></a>
                        <a href="#" class="fab fa-linkedin"></a>
                    </div>
                </div>

                <div class="box">
                    <h3>contact info</h3>
                    <a href="#" class="links"> <i class="fas fa-phone"></i> +123-456-7890 </a>
                    <a href="#" class="links"> <i class="fas fa-phone"></i> +111-222-3333 </a>
                    <a href="#" class="links"> <i class="fas fa-envelope"></i> abc@gmail.com </a>
                    <a href="#" class="links"> <i class="fas fa-map-marker-alt"></i> ktm, nepal - 400104 </a>
                </div>

                <div class="box">
                    <h3>quick links</h3>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> home </a>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> features </a>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> products </a>
                    <a href="#" class="links"> <i class="fas fa-arrow-right"></i> categories </a>
                </div>



            </div>

            <div class="credit"> created by <span> mr. web designer </span> | all rights reserved </div>

        </section>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
    </html>


}

car-rental/Views/Shared/_PartialLogin.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager




<div class="d-flex align-items-center justify-content-between">
    @if (SignInManager.IsSignedIn(User))
    {


        <div class="pe-3">
            <a asp-controller="Account" asp-action="Profile">@UserManager.GetUserName(User) Profile</a>
        </div>


        <div>
            <a asp-controller="Authentication" asp-action="Logout">Logout</a>
        </div>

        <div class="icons">
            <div class="fas fa-user" id="login-btn"></div>
        </div>


    }
    else
    {
        <div class="pe-3">
            <a class="btn-main btn-main-fill id="register" asp-controller="Authentication" asp-action="Register">Register</a>
        </div>
        <div class="pe-3">
            <a class="btn-main btn-main-fill id="register" asp-controller="Authentication" asp-action="RegisterStaff">Register Staff</a>
        </div>

        <div class="">
            <a class="btn-main btn-main-outline" id="login" asp-controller="Authentication" asp-action="Login">Login</a>

        </div>
    }
    </>